export const images = {
  splash: require('../assets/images/Splash.png.png'),
  eye: require('../assets/images/eye.png.png'),
  hide: require('../assets/images/hide.png.png'),
  bin: require('../assets/images/Bin.png.png'),
  vector: require('../assets/images/Vector.png'),
  Avtaar: require('../assets/images/Avtaar.png'),
  Tick: require('../assets/images/Tick.png'),
  AddSchool: require('../assets/images/AddSchool.png'),
  File: require('../assets/images/File.png'),
  Hamburger: require('../assets/images/Hamburger.png'),
  Home: require('../assets/images/Home.png'),
  FieldTrack: require('../assets/images/FieldTrack.png'),
  Allowance: require('../assets/images/Allowance.png'),
  AddSchooll: require('../assets/images/AddSchooll.png'),
  Reports: require('../assets/images/Reports.png'),
  Logout: require('../assets/images/Logout.png'),
  ResetPassword: require('../assets/images/ResetPassword.png'),
  Play: require('../assets/images/Play.png'),
  Pause: require('../assets/images/Pause.png'),
  Upload: require('../assets/images/Upload.png'),
  HeaderImage: require('../assets/images/Rectangle.png'),
  imageU: require('../assets/images/imageU.png'),
  View: require('../assets/images/View.png'),
  delete: require('../assets/images/delete.png'),
  road: require('../assets/images/road.png'),
}; 